# Generated by Django 2.0.2 on 2018-03-28 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_auto_20180320_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='subtitule',
            new_name='subtitle',
        ),
    ]
